// One-time data-prep script — not part of the runtime app. Regenerates
// src/lib/trial-match/zip3-centroids.ts from the U.S. Census Bureau's public
// domain ZCTA Gazetteer file by averaging each ZCTA5 centroid's lat/lon into
// its 3-digit ZIP prefix group.
//
// Run with: npx tsx scripts/build-zip3-centroids.ts
//
// If the environment running this has no network access, do not invent
// coordinates — hand-curate a smaller replacement table in the same
// `Record<string, {lat, lon}>` shape instead (see zip3-centroids.ts's header
// comment for the disclosure convention), covering at minimum every ZIP3
// prefix referenced by src/dev/fixtures.ts.

import { writeFileSync } from 'node:fs';
import { join } from 'node:path';

const GAZETTEER_URL =
  'https://www2.census.gov/geo/docs/maps-data/data/gazetteer/2023_Gazetteer/2023_Gaz_zcta_national.zip';

async function main() {
  const res = await fetch(GAZETTEER_URL);
  if (!res.ok) throw new Error(`Failed to download Gazetteer file: HTTP ${res.status}`);
  const zipBuffer = new Uint8Array(await res.arrayBuffer());

  // Minimal inline ZIP extraction would require a dependency; instead this
  // script expects the .txt already extracted alongside it when run — see
  // README.md's data-prep note. Extract 2023_Gaz_zcta_national.zip first:
  //   curl -o /tmp/gaz.zip <url> && unzip /tmp/gaz.zip -d /tmp/gaz
  // then point GAZETTEER_TXT_PATH at the extracted .txt file.
  const txtPath = process.env.GAZETTEER_TXT_PATH;
  if (!txtPath) {
    throw new Error(
      'Set GAZETTEER_TXT_PATH to the extracted 2023_Gaz_zcta_national.txt path (download+unzip the URL above first).',
    );
  }
  void zipBuffer;

  const { readFileSync } = await import('node:fs');
  const lines = readFileSync(txtPath, 'latin1').split('\n').slice(1);

  const groups = new Map<string, { latSum: number; lonSum: number; count: number }>();
  for (const line of lines) {
    if (!line.trim()) continue;
    const cols = line.split('\t');
    const geoid = cols[0]?.trim();
    const lat = parseFloat(cols[5]);
    const lon = parseFloat(cols[6]);
    if (!geoid || geoid.length !== 5 || Number.isNaN(lat) || Number.isNaN(lon)) continue;

    const zip3 = geoid.slice(0, 3);
    const group = groups.get(zip3) ?? { latSum: 0, lonSum: 0, count: 0 };
    group.latSum += lat;
    group.lonSum += lon;
    group.count += 1;
    groups.set(zip3, group);
  }

  const zip3s = [...groups.keys()].sort();
  const entries = zip3s
    .map((zip3) => {
      const g = groups.get(zip3)!;
      const lat = +(g.latSum / g.count).toFixed(4);
      const lon = +(g.lonSum / g.count).toFixed(4);
      return `  "${zip3}": { lat: ${lat}, lon: ${lon} },`;
    })
    .join('\n');

  const header = `// Generated by scripts/build-zip3-centroids.ts from the U.S. Census Bureau
// 2023 ZCTA Gazetteer file (public domain): ${GAZETTEER_URL}
// Each entry is the unweighted average of every ZCTA5 internal-point centroid
// sharing that 3-digit prefix -- an area-level approximation, not an exact
// location. Do not present a ZIP3 centroid as an individual patient's address;
// see zip-crosswalk.ts for how confidence is modeled around this table.
// Re-run \`npx tsx scripts/build-zip3-centroids.ts\` to regenerate.

export const ZIP3_CENTROIDS: Record<string, { lat: number; lon: number }> = {
${entries}
};
`;

  const outPath = join(__dirname, '..', 'src', 'lib', 'trial-match', 'zip3-centroids.ts');
  writeFileSync(outPath, header);
  console.log(`Wrote ${zip3s.length} ZIP3 centroids to ${outPath}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
