import type { VocabEntry } from "./types";

// Small curated bundled subset of ICD-10-CM, scoped to common primary-care
// chief complaints — enough to exercise the diagnosis-gap module end to end
// without depending on a licensed full code set. Each entry's `keywords`
// widen retrieval beyond words that appear verbatim in `description`.
export const ICD10_ENTRIES: VocabEntry[] = [
  { code: "Z00.00", description: "Encounter for general adult medical examination without abnormal findings", system: "ICD-10-CM", meta: { keywords: ["annual", "physical", "wellness", "checkup", "exam"] } },
  { code: "R51.9", description: "Headache, unspecified", system: "ICD-10-CM", meta: { keywords: ["headache", "head pain", "migraine-like"] } },
  { code: "G43.909", description: "Migraine, unspecified, not intractable, without status migrainosus", system: "ICD-10-CM", meta: { keywords: ["migraine"] } },
  { code: "J06.9", description: "Acute upper respiratory infection, unspecified", system: "ICD-10-CM", meta: { keywords: ["cold", "uri", "sore throat", "congestion", "cough"] } },
  { code: "J02.9", description: "Acute pharyngitis, unspecified", system: "ICD-10-CM", meta: { keywords: ["sore throat", "pharyngitis", "throat pain"] } },
  { code: "J20.9", description: "Acute bronchitis, unspecified", system: "ICD-10-CM", meta: { keywords: ["bronchitis", "cough", "chest congestion"] } },
  { code: "R05.9", description: "Cough, unspecified", system: "ICD-10-CM", meta: { keywords: ["cough"] } },
  { code: "R07.9", description: "Chest pain, unspecified", system: "ICD-10-CM", meta: { keywords: ["chest pain", "chest discomfort"] } },
  { code: "R06.02", description: "Shortness of breath", system: "ICD-10-CM", meta: { keywords: ["shortness of breath", "dyspnea", "can't catch my breath", "breathless"] } },
  { code: "M54.50", description: "Low back pain, unspecified", system: "ICD-10-CM", meta: { keywords: ["back pain", "lower back", "lumbago"] } },
  { code: "M54.2", description: "Cervicalgia", system: "ICD-10-CM", meta: { keywords: ["neck pain"] } },
  { code: "M25.50", description: "Pain in unspecified joint", system: "ICD-10-CM", meta: { keywords: ["joint pain", "arthralgia"] } },
  { code: "M79.10", description: "Myalgia, unspecified site", system: "ICD-10-CM", meta: { keywords: ["muscle pain", "myalgia", "body aches"] } },
  { code: "R10.9", description: "Unspecified abdominal pain", system: "ICD-10-CM", meta: { keywords: ["abdominal pain", "stomach pain", "belly pain", "abdomen"] } },
  { code: "R10.11", description: "Right upper quadrant pain", system: "ICD-10-CM", meta: { keywords: ["right upper quadrant", "ruq pain"] } },
  { code: "K21.9", description: "Gastro-esophageal reflux disease without esophagitis", system: "ICD-10-CM", meta: { keywords: ["gerd", "reflux", "heartburn"] } },
  { code: "R11.10", description: "Vomiting, unspecified", system: "ICD-10-CM", meta: { keywords: ["vomiting", "nausea", "throwing up"] } },
  { code: "R19.7", description: "Diarrhea, unspecified", system: "ICD-10-CM", meta: { keywords: ["diarrhea", "loose stools"] } },
  { code: "N39.0", description: "Urinary tract infection, site not specified", system: "ICD-10-CM", meta: { keywords: ["uti", "urinary tract infection", "dysuria", "burning urination"] } },
  { code: "R30.0", description: "Dysuria", system: "ICD-10-CM", meta: { keywords: ["painful urination", "burning with urination"] } },
  { code: "R42", description: "Dizziness and giddiness", system: "ICD-10-CM", meta: { keywords: ["dizziness", "lightheaded", "vertigo"] } },
  { code: "R53.83", description: "Other fatigue", system: "ICD-10-CM", meta: { keywords: ["fatigue", "tired", "exhaustion", "low energy"] } },
  { code: "R50.9", description: "Fever, unspecified", system: "ICD-10-CM", meta: { keywords: ["fever", "chills", "temperature"] } },
  { code: "H66.90", description: "Otitis media, unspecified, unspecified ear", system: "ICD-10-CM", meta: { keywords: ["ear infection", "ear pain", "otitis"] } },
  { code: "H57.10", description: "Eye pain, unspecified eye", system: "ICD-10-CM", meta: { keywords: ["eye pain"] } },
  { code: "L30.9", description: "Dermatitis, unspecified", system: "ICD-10-CM", meta: { keywords: ["rash", "skin irritation", "dermatitis"] } },
  { code: "R21", description: "Rash and other nonspecific skin eruption", system: "ICD-10-CM", meta: { keywords: ["rash", "skin eruption", "hives"] } },
  { code: "M25.561", description: "Pain in right knee", system: "ICD-10-CM", meta: { keywords: ["knee pain", "right knee"] } },
  { code: "M25.562", description: "Pain in left knee", system: "ICD-10-CM", meta: { keywords: ["knee pain", "left knee"] } },
  { code: "M54.9", description: "Dorsalgia, unspecified", system: "ICD-10-CM", meta: { keywords: ["back pain", "spine pain"] } },
  { code: "I10", description: "Essential (primary) hypertension", system: "ICD-10-CM", meta: { keywords: ["hypertension", "high blood pressure", "htn follow up"] } },
  { code: "E11.9", description: "Type 2 diabetes mellitus without complications", system: "ICD-10-CM", meta: { keywords: ["diabetes", "type 2 diabetes", "diabetic follow up", "a1c"] } },
  { code: "E78.5", description: "Hyperlipidemia, unspecified", system: "ICD-10-CM", meta: { keywords: ["high cholesterol", "hyperlipidemia", "lipid panel"] } },
  { code: "E66.9", description: "Obesity, unspecified", system: "ICD-10-CM", meta: { keywords: ["obesity", "weight management"] } },
  { code: "F41.9", description: "Anxiety disorder, unspecified", system: "ICD-10-CM", meta: { keywords: ["anxiety", "anxious", "worry"] } },
  { code: "F32.9", description: "Major depressive disorder, single episode, unspecified", system: "ICD-10-CM", meta: { keywords: ["depression", "depressed mood", "low mood"] } },
  { code: "G47.00", description: "Insomnia, unspecified", system: "ICD-10-CM", meta: { keywords: ["insomnia", "trouble sleeping", "can't sleep"] } },
  { code: "J45.909", description: "Unspecified asthma, uncomplicated", system: "ICD-10-CM", meta: { keywords: ["asthma", "wheezing"] } },
  { code: "J30.9", description: "Allergic rhinitis, unspecified", system: "ICD-10-CM", meta: { keywords: ["allergies", "seasonal allergies", "rhinitis", "runny nose", "sneezing"] } },
  { code: "R60.9", description: "Edema, unspecified", system: "ICD-10-CM", meta: { keywords: ["swelling", "edema"] } },
  { code: "S93.401A", description: "Sprain of unspecified ligament of right ankle, initial encounter", system: "ICD-10-CM", meta: { keywords: ["ankle sprain", "twisted ankle", "right ankle"] } },
  { code: "R41.840", description: "Attention and concentration deficit", system: "ICD-10-CM", meta: { keywords: ["trouble concentrating", "attention"] } },
  { code: "N94.6", description: "Dysmenorrhea, unspecified", system: "ICD-10-CM", meta: { keywords: ["menstrual pain", "cramps", "dysmenorrhea"] } },
  { code: "Z71.3", description: "Dietary counseling and surveillance", system: "ICD-10-CM", meta: { keywords: ["diet counseling", "nutrition"] } },
];